Product.create!([
  {name: "Marucci AP5 Albert Pujols Custom Pro Maple Bat", price: "169.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/19MCCACSTMP5PRMDLWBT_Custom?wid=685&fmt=jpg", description: "Inspired by the core design used by one of the game’s greatest sluggers, the Marucci® AP5 Albert Pujols Custom Pro Maple Bat lays down the foundation for powerful performance at the plate while you personalize a number of key details for a completely unique experience. This bat is bone-rubbed to deliver a denser, more durable design, and offers an end-loaded feel to bolster the impact of your swing to send the ball sailing."},
  {name: "Easton Pro X Catcher's Helmet", price: "169.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/18ETSAPRXCTCHRSHLCTC_Black_Silver?qlt=70&wid=1100&fmt=webp", description: "Equipped with industry-leading Poron XRD® padding to maximize impact resistance, the Easton® Pro X™ Catcher’s Helmet is optimized for elite players that need top-tier protection behind the plate. This top-of-the-line helmet also utilizes BioDri™ liner to accelerate moisture absorption, helping to keep you dry as the game wares on."},
  {name: "Wilson 11.5'' 1786 A2000 Series Glove", price: "259.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/18WILA11520001786BGL_Brown_Blonde?wid=685&fmt=jpg", description: "Materials that consistently perform and dependable construction, the 2019 Wilson® A2000® Series Gloves are preferred by hard-working players for their unmatched feel, rugged durability and perfect break-in . This 11.5’’ model has a 1786 pattern, with an I-Web that infielders prefer for a more shallow pocket."},
  {name: "Heater Deuce 75 Pitching Machine w/ Xtender 36' Batting Cage", price: "1299.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/17HEAUDC75XTNDR36TRA?qlt=70&wid=1100&fmt=webp", description: "Two-wheel fastball and breaking ball pitching machine with an auto-ball feeder, the Heater® Deuce 75 Pitching Machine combines with the 36’ x 12’ x 10’ Batting Cage to give everything teams need to have a professional practice"},
  {name: "adidas Men's adizero Afterburner 6 Grail 8-Bit Baseball Cleats", price: "130.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/19ADIMFTRBRNR6GRLCLT_Royal_White?wid=685&fmt=jpg", description: "Conquer the opposition in the adidas® Afterburner 6 Grail 8-Bit Baseball cleat. The Afterburner 6 cleat has a bootie construction and widened lacing system for a snug locked in fit. A mixed spike SPRINTFRAME plate delivers the best of molded and metal spikes in one cleat."},
  {name: "EvoShield Adult XGT G2S Batting Gloves", price: "59.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/18EVSMVWHTXGTG2SBBTG_White_White?qlt=70&wid=1100&fmt=webp", description: "Designed with a premium embossed sheepskin leather palm and featuring Gel-to-Shell™ integration, the EvoShield® Adult XGT™ G2S Batting Gloves balance superior comfort and protection for elite-level performance. The gloves are also equipped with a lycra spandex backhand and double-stitched seams, helping increase its longevity and breathability as you swing for the fences during your next plate appearance."},
  {name: "Easton Senior Elite X Batting Helmet w/ Universal Jaw Guard", price: "59.0", image_url: "https://dks.scene7.com/is/image/GolfGalaxy/19ETSSLTXNVJGRHBSBTH_Black_White?qlt=70&wid=1100&fmt=webp", description: "Utilizing an ABS thermoplastic shell that includes an extended jaw guard that can be installed on either side, the Easton® Senior Elite X Batting Helmet provides excellent coverage against potential danger when stepping into the box this season. This Senior size helmet fits most sizes from 7-1/8’’ to 7-1/2’’ and includes three difference layers of impact absorbing density foam to reinforce protection."}
])
